### ISSUE TITLE
panic "Parsing methods": 'called `Result::unwrap()` on an `Err` value: "Anonymous type"'

### ISSUE THREAD

**Issue by alexchandel** [rust-qt/cpp_to_rust#17]
cpp_to_rust panics and dies right after printing "Parsing methods...". The stack trace begins in `cpp_to_rust::cpp_parser::CppParser::parse_canonical_type`, but I'm not sure where. Unfortunately `unwrap()` is called several times within that function.

**Comment by alexchandel** [comment]
```c++
get_children refers to itself!
Parsing methods...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Anonymous type"', ../src/libcore/result.rs:799
stack backtrace:
   1:        0x10d2f469a - std::sys::backtrace::tracing::imp::write::h4b09e6e8c01db097
   2:        0x10d2fb46f - std::panicking::default_hook::{{closure}}::h1d3243f546573ff4
   3:        0x10d2fa485 - std::panicking::default_hook::h96c288d728df3ebf
   4:        0x10d2faa96 - std::panicking::rust_panic_with_hook::hb1322e5f2588b4db
   5:        0x10d2fa934 - std::panicking::begin_panic::hfbeda5aad583dc32
   6:        0x10d2fa852 - std::panicking::begin_panic_fmt::h4fe9fb9d5109c4bf
   7:        0x10d2fa7b7 - rust_begin_unwind
   8:        0x10d3270ed - core::panicking::panic_fmt::h4395919ece15c671
   9:        0x10c6ac8b2 - core::result::unwrap_failed::h9afc159b7bc64e75
  10:        0x10c672a3d - <core::result::Result<T, E>>::unwrap::h53c94d0133074ed1
  11:        0x10c9c2a83 - cpp_to_rust::cpp_parser::CppParser::parse_canonical_type::h24fa0cc62711804e
  12:        0x10c9c0d75 - cpp_to_rust::cpp_parser::CppParser::parse_type::h98b3d065dd1540cb
  13:        0x10c9c5f63 - cpp_to_rust::cpp_parser::CppParser::parse_function::hd3e1fddb56c4aa68
  14:        0x10c9d0a9a - cpp_to_rust::cpp_parser::CppParser::parse_methods::h2f698678aaa4b7b0
  15:        0x10c9d15a8 - cpp_to_rust::cpp_parser::CppParser::parse_methods::h2f698678aaa4b7b0
  16:        0x10c9d15a8 - cpp_to_rust::cpp_parser::CppParser::parse_methods::h2f698678aaa4b7b0
  17:        0x10ca9759b - cpp_to_rust::cpp_parser::run::{{closure}}::h8b1ca2094dcb61b0
  18:        0x10c9ba7c5 - cpp_to_rust::cpp_parser::run_clang::hfe541cd3d2a67628
  19:        0x10c9bae70 - cpp_to_rust::cpp_parser::run::h90c400bca5e78c03
  20:        0x10c9d6633 - cpp_to_rust::launcher::run::hcafbead91358ffd5
  21:        0x10c5da17a - cpp_to_rust_bin::main::he1e5ea769cf403fc
  22:        0x10d2fba2a - __rust_maybe_catch_panic
  23:        0x10d2f9fc6 - std::rt::lang_start::haaae1186de9de8cb
  24:        0x10c5da4f9 - main
```

**Comment by Riateche** [comment]
Your stack trace doesn't have line numbers. Did you try to build in debug mode?

**Comment by alexchandel** [comment]
Yeah I built in debug mode, rustc 1.13.0-nightly, x86_64-apple-darwin. I can't recall ever seeing a panic include line numbers in the stack trace.

**Comment by Riateche** [comment]
It seems that line numbers only work on Linux: https://github.com/rust-lang/rust/issues/24346
That's sad. Can you get line numbers with lldb, as suggested [here](https://github.com/rust-lang/rust/issues/24346#issuecomment-221375810)?

**Comment by alexchandel** [comment]
```
(lldb) bt
error: need to add support for DW_TAG_base_type 'char' encoded with DW_ATE = 0x8, bit_size = 32
* thread #1: tid = 0x2870d0, 0x0000000100d2f740 cpp_to_rust_bin`rust_begin_unwind, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
  * frame #0: 0x0000000100d2f740 cpp_to_rust_bin`rust_begin_unwind
    frame #1: 0x0000000100d5c0ae cpp_to_rust_bin`core::panicking::panic_fmt::h4395919ece15c671 + 126
    frame #2: 0x00000001000e1873 cpp_to_rust_bin`core::result::unwrap_failed<collections::string::String>(msg=(data_ptr = "called `Result::unwrap()` on an `Err` value", length = 43), error=String @ 0x00007fff5fbf0498) + 387 at macros.rs:29
    frame #3: 0x00000001000a79be cpp_to_rust_bin`core::result::{{impl}}::unwrap<collections::string::String,collections::string::String>(self=Result<collections::string::String, collections::string::String> @ 0x00007fff5fbf0580) + 382 at result.rs:737
    frame #4: 0x00000001003f7a44 cpp_to_rust_bin`cpp_to_rust::cpp_parser::{{impl}}::parse_canonical_type(self=0x00007fff5fbf7278, type1=Type @ 0x00007fff5fbf1c00, context_class=Option<clang::Entity> @ 0x00007fff5fbf1bd8, context_method=Option<clang::Entity> @ 0x00007fff5fbf1bb0) + 2068 at cpp_parser.rs:693
    frame #5: 0x00000001003f5d36 cpp_to_rust_bin`cpp_to_rust::cpp_parser::{{impl}}::parse_type(self=0x00007fff5fbf7278, type1=Type @ 0x00007fff5fbf2550, context_class=Option<clang::Entity> @ 0x00007fff5fbf2528, context_method=Option<clang::Entity> @ 0x00007fff5fbf2500) + 806 at cpp_parser.rs:530
    frame #6: 0x00000001003faf24 cpp_to_rust_bin`cpp_to_rust::cpp_parser::{{impl}}::parse_function(self=0x00007fff5fbf7278, entity=Entity @ 0x00007fff5fbf4d90) + 2356 at cpp_parser.rs:841
    frame #7: 0x0000000100405a5b cpp_to_rust_bin`cpp_to_rust::cpp_parser::{{impl}}::parse_methods(self=0x00007fff5fbf7278, entity=Entity @ 0x00007fff5fbf5920) + 779 at cpp_parser.rs:1317
    frame #8: 0x0000000100406569 cpp_to_rust_bin`cpp_to_rust::cpp_parser::{{impl}}::parse_methods(self=0x00007fff5fbf7278, entity=Entity @ 0x00007fff5fbf6490) + 3609 at cpp_parser.rs:1358
    frame #9: 0x0000000100406569 cpp_to_rust_bin`cpp_to_rust::cpp_parser::{{impl}}::parse_methods(self=0x00007fff5fbf7278, entity=Entity @ 0x00007fff5fbf7000) + 3609 at cpp_parser.rs:1358
    frame #10: 0x00000001004cc55c cpp_to_rust_bin`cpp_to_rust::cpp_parser::run::{{closure}}(translation_unit=Entity @ 0x00007fff5fbf7360) + 540 at cpp_parser.rs:197
    frame #11: 0x00000001003ef786 cpp_to_rust_bin`cpp_to_rust::cpp_parser::run_clang<(cpp_to_rust::cpp_parser::CppParser, collections::vec::Vec<cpp_to_rust::serializable::CppMethod>),closure>(config=0x00007fff5fbf82b8, cpp_code=Option<collections::string::String> @ 0x00007fff5fbf7bf0, f=closure @ 0x00007fff5fbf7be0) + 3734 at cpp_parser.rs:180
    frame #12: 0x00000001003efe31 cpp_to_rust_bin`cpp_to_rust::cpp_parser::run(config=CppParserConfig @ 0x00007fff5fbf8350, dependency_types=0x00007fff5fbfc488) + 561 at cpp_parser.rs:188
    frame #13: 0x000000010040b5f4 cpp_to_rust_bin`cpp_to_rust::launcher::run(env=BuildEnvironment @ 0x00007fff5fbfc940) + 9316 at launcher.rs:266
    frame #14: 0x000000010000f13b cpp_to_rust_bin`cpp_to_rust_bin::main + 1675 at main.rs:50
    frame #15: 0x0000000100d309eb cpp_to_rust_bin`__rust_maybe_catch_panic + 27
    frame #16: 0x0000000100d2ef87 cpp_to_rust_bin`std::rt::lang_start::haaae1186de9de8cb + 391
    frame #17: 0x000000010000f4ba cpp_to_rust_bin`main + 42
    frame #18: 0x00007fff983ef5ad libdyld.dylib`start + 1
```

**Comment by alexchandel** [comment]
The line:
```rust
      TypeKind::Enum => {
        Ok(CppType {
          base: CppTypeBase::Enum {
            name: get_full_name(type1.get_declaration().unwrap()).unwrap(), // 693
          },
          is_const: is_const,
          indirection: CppTypeIndirection::None,
        })
```
